# Generated by Django 4.1.3 on 2022-11-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("url", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="url",
            old_name="shortened_url",
            new_name="shorten_url",
        ),
    ]
