# Generated by Django 4.1.3 on 2022-11-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("url", "0003_url_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="slug",
            field=models.SlugField(blank=True, default=""),
        ),
    ]
