# Generated by Django 4.1.3 on 2022-11-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("url", "0004_url_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
