# Generated by Django 4.1.3 on 2022-11-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("url", "0005_url_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="url",
            name="slug",
        ),
        migrations.AlterField(
            model_name="url",
            name="shorten_url",
            field=models.SlugField(blank=True, default=""),
        ),
    ]
