# Generated by Django 4.1.3 on 2022-11-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("url", "0006_remove_url_slug_alter_url_shorten_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="last_access",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
