# Generated by Django 4.1.3 on 2022-11-09 23:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("url", "0008_remove_url_id_alter_url_count_alter_url_last_access_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="original_url",
            field=models.CharField(
                help_text="Enter the URL you want to shorten",
                max_length=250,
                validators=[
                    django.core.validators.URLValidator,
                    django.core.validators.MinLengthValidator(2),
                ],
                verbose_name="Original URL",
            ),
        ),
    ]
