# Generated by Django 4.1.3 on 2022-11-09 23:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("url", "0009_alter_url_original_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="original_url_link",
            field=models.URLField(
                help_text="original_url with protocol if needed",
                max_length=250,
                null=True,
                validators=[
                    django.core.validators.URLValidator,
                    django.core.validators.MinLengthValidator(2),
                ],
                verbose_name="Original URL url",
            ),
        ),
        migrations.AlterField(
            model_name="url",
            name="original_url",
            field=models.CharField(
                help_text="Enter the URL you want to shorten",
                max_length=250,
                validators=[django.core.validators.MinLengthValidator(2)],
                verbose_name="Original URL text",
            ),
        ),
    ]
