# Generated by Django 4.1.3 on 2022-11-09 23:30

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import url.models


class Migration(migrations.Migration):

    dependencies = [
        ("url", "0010_url_original_url_link_alter_url_original_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="last_access",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                validators=[url.models.validate_date],
                verbose_name="Last access date",
            ),
        ),
        migrations.AlterField(
            model_name="url",
            name="original_url",
            field=models.CharField(
                help_text="Enter the URL you want to shorten",
                max_length=250,
                validators=[
                    url.models.validate_url_text,
                    django.core.validators.MinLengthValidator(2),
                ],
                verbose_name="Original URL text",
            ),
        ),
        migrations.AlterField(
            model_name="url",
            name="original_url_link",
            field=models.URLField(
                help_text="original_url with protocol if needed",
                max_length=250,
                null=True,
                validators=[
                    url.models.validate_url_link,
                    django.core.validators.URLValidator,
                    django.core.validators.MinLengthValidator(2),
                ],
                verbose_name="Original URL url",
            ),
        ),
        migrations.AlterField(
            model_name="url",
            name="pub_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                validators=[url.models.validate_date],
                verbose_name="Publication date",
            ),
        ),
    ]
