# Generated by Django 4.1.3 on 2022-11-11 18:28

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ("url", "0011_alter_url_last_access_alter_url_original_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="shorten_url_length",
            field=models.IntegerField(
                default=5,
                validators=[
                    django.core.validators.MaxValueValidator(8),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="url",
            name="shorten_url",
            field=models.SlugField(
                max_length=8,
                primary_key=True,
                serialize=False,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
                verbose_name="Shorten URL slug",
            ),
        ),
    ]
